package com.wajiraenterprises.util;

public enum ModuleList {
    EMPLOYEE, USER, PRIVILAGE, DESIGNATION, USERPASSWORDCHANGE, COMPANY, VEHICLE, SHIPMENT, HSCODE, DOCUMENTS, CLEARINGPROCESS, DELIVERYREQUEST, DELIVERYCONFIRMATION, DELIVERY, GRN, INVENTORY, GDN, CUSTOMERACCEPTENCE,INVOICE,PAYMENT,CREDIT,CHEQUE,ACTIVITYLOG,
    DELIVERYORDER, CUSDEC, TAXPAYMENT, PANELEXAMINATION,
}
